spring:
  application:
    name: feign-client-app
    rest:
      client:
        basic-auth:
          username: username
          password: password
          host: http://localhost:8081
        oauth2:
          host: http://localhost:8083
          token:
            url: http://localhost:8084
            client-id: client-id
            client-secret: client-secret
        ntlm:
          host: http://localhost:8085
          username: username
          password: password
          workstation: workstation
          domain: domain
        api-key:
          host: http://localhost:8086
          key: key
        jwt:
          host: http://localhost:8087